#!/usr/bin/env bash
FE_DIST_DIR=${FE_DIST_DIR:="../../dist/dev"}
FE_URL_API=${FE_URL_API:="http://127.0.0.1:8000/api"}
FE_URL_ROOT=${FE_URL_ROOT:="http://127.0.0.1:8081"}
FE_PORT=${FE_PORT:="9000"}
FE_LIVE_PORT=${FE_PORT:="35729"}

FE_SERVER_TYPE=${FE_SERVER_TYPE:="dev"}

cd backend-angular/master

if [ $FE_SERVER_TYPE = "dev" ]
then
   gulp  --output $FE_DIST_DIR --port $FE_PORT --liveport $FE_LIVE_PORT --urlapi $FE_URL_API --urlroot $FE_URL_ROOT 
else
   sed -i '/url_api/c\"url_api": "'$FE_URL_API'",' $FE_DIST_DIR/app/js/ngConstants.js
   sed -i '/url_root/c\"url_root": "'$FE_URL_ROOT'"' $FE_DIST_DIR/app/js/ngConstants.js
   /usr/sbin/nginx -g "daemon off;"
fi
